# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd8df313c5065f0df4f3d215dbc0cf935c638f7cdadb9b2a359a8a310f7e41d3eaeb796284983b9efed32d466936a90851b86a6b1f13924dff920c75a2f3eee6

test:
  secret_key_base: e751c527f44f00facad72856cbde75c8b987c45e40b13611bbcf396e3597862ba55c0fdfb6425c47614635e77b80c69ea8aa846b6bab5becc3bd3e19376b2fa4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
